 - name: Install Elixir and Erlang on Debian
  block:
    - name: Add RabbitMQ Erlang repository
      apt_repository:
        repo: ppa:rabbitmq/rabbitmq-erlang
        update_cache: yes
    
    - name: Update apt cache and install packages
      apt:
        name:
          - elixir
          - erlang-dev
          - erlang-xmerl
        state: latest
        update_cache: yes
  become: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install Elixir on Arch Linux
  pacman:
    name: elixir
    state: present
  become: yes
  when: ansible_os_family == 'Archlinux'

- name: Install Elixir and Erlang on Fedora
  dnf:
    name:
      - elixir
      - erlang
    state: latest
  become: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'

