---
- name: Install
  ansible.builtin.package:
    name:
      - open-vm-tools
    state: latest
  become: yes

- name: Enable vmtoolsd
  ansible.builtin.systemd:
    enabled: yes
    name: vmtoolsd
    state: started
  become: yes