---
- hosts: localhost
  connection: local
  vars_files:
    - ./group_vars/versions.yml
    - ./vars.yml
    - ./group_vars/all
  tasks:
    - name: Extract roles from the selected role group
      set_fact:
        roles: "{{ vars[role_group] }}"
      tags:
        - always

    - name: Display roles
      debug: 
        var: roles
      tags:
        - always

    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always

  handlers:
    # TODO this is a bit rubbish, but it works for now
    include:
      - ./roles/ssh/handlers/main.yml

