- name: Install OpenSSH server
  ansible.builtin.package:
    name: openssh-server
    state: present
  become: yes

- name: Configure SSH to listen on a custom port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: "Port {{ ssh_port }}"
    state: present
  become: yes
  notify:
    - restart ssh

- name: Ensure SSH is running and enabled
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
  become: yes