---
- name: Ensure Git is installed
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Configure Git for the user
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_env.USER }}"