---
- name: Download Go tarball
  ansible.builtin.get_url:
    url: "{{ go_download_url }}"
    dest: "/tmp/{{ go_tarball }}"
    mode: '0755'

- name: Remove any previous Go installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  become: yes

- name: Extract Go tarball to /usr/local
  ansible.builtin.unarchive:
    src: "/tmp/{{ go_tarball }}"
    dest: /usr/local
    remote_src: yes
    creates: "/usr/local/go/bin/go"
  become: yes

- name: Append PATH export to .bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export PATH=$PATH:/usr/local/go/bin'
    state: present
    insertafter: EOF
    create: yes
    validate: 'bash -n %s'
    regexp: '^export PATH=.*:/usr/local/go/bin'
  become: no

- name: Append PATH export to .zshrc
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    line: 'export PATH=$PATH:/usr/local/go/bin'
    state: present
    insertafter: EOF
    create: yes
    validate: 'zsh -n %s'
    regexp: '^export PATH=.*:/usr/local/go/bin'
  become: no

