---
 - name: Fetch the latest fd release version from GitHub
  uri:
    url: https://api.github.com/repos/sharkdp/fd/releases/latest
    return_content: yes
    headers:
      Accept: application/vnd.github.v3+json
  register: github_release
  become: yes  
  when: ansible_os_family == "Debian"

- name: Set fd version fact
  set_fact:
    fd_version: "{{ github_release.json.tag_name[1:] }}"
  become: yes  
  when: ansible_os_family == "Debian"

- name: Download the fd Debian package
  get_url:
    url: "https://github.com/sharkdp/fd/releases/latest/download/fd_{{ fd_version }}_amd64.deb"
    dest: "/tmp/fd.deb"
    mode: '0755'
  become: yes  
  when: ansible_os_family == "Debian"

- name: Install fd from the Debian package
  apt:
    deb: "/tmp/fd.deb"
  become: yes  
  when: ansible_os_family == "Debian"

- name: Remove the downloaded fd Debian package
  file:
    path: "/tmp/fd.deb"
    state: absent
  become: yes  
  when: ansible_os_family == "Debian"

- name: Install fd on Fedora
  dnf:
    name: fd-find
    state: present
  become: yes  
  when: ansible_os_family == "RedHat"

- name: Install fd on Arch Linux
  pacman:
    name: fd
    state: present
  become: yes  
  when: ansible_os_family == "Archlinux"
