---
- name: Dependencies
  ansible.builtin.package:
    name:
      - cmake
      - curl
      - ninja-build
      - gettext
      - unzip
    state: latest
  become: yes

- name: Clone
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    # single_branch: yes
    update: yes
    version: "{{ neovim_version | default('master') }}"
  register: clone

- name: Build
  make:
    chdir: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: clone.changed

- name: Install
  make:
    chdir: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
    target: install
  become: yes
  when: clone.changed

- name: Remove build folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim/build"
    state: absent
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Clone
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/nvim"
    force: yes
    repo: git@github.com:maccalsa/nvim-kickstart.git
    # single_branch: yes
    update: yes
    version: "{{ neovim_version | default('main') }}"
  register: clone
