---
- name: Ensure bat is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - bat
    - batcat  # Include this if needed for Debian/Ubuntu as a fallback
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ignore_errors: yes  # Useful if one of the packages is not found, continue with others
  become: yes

- name: Ensure bat is installed (for non-Debian/Ubuntu)
  ansible.builtin.package:
    name: bat
    state: present
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'
  become: yes